- name: javac
  weight: 50
  condition: 40
  context: ''
  configuration:
- name: junit
  weight: 50
  condition: 40
  context: ''
  depends-on:
    - javac
  configuration:
    test_files:
      repository: this
      branch: master
      sha: latest
    timeout: 1m
